server:
  port: 8081
  
spring:
  application:
    name: assessment-apigateway-ms
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable DiscoveryClient for routing through Eureka
      routes:
        # Static route example (optional)
        - id: employee-route
          uri: lb://assessment-employee-ms
          predicates:
            - Path=/employee/**
          filters:
            - JwtAuthenticationFilter
        
        # Dynamic route example with service discovery (via Eureka)
        - id: admin-route
          uri: lb://assessment-admin-ms  # Replace with your actual service name registered in Eureka
          predicates:
            - Path=/admin/**
          filters:
            - JwtAuthenticationFilter
            
        - id: auth-route
          uri: lb://assessment-authentication-ms
          predicates:
            - Path=/auth/**
